import type { NextPage } from "next";
import Head from "next/head";
import { Box, Typography } from "@mui/material";
import { companyName } from "../src/config";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box component="div" height="100%">
        <Typography variant="h2" color="primary.main">
          Welcome to {companyName}
        </Typography>
      </Box>
    </>
  );
};

export default Home;
